<?php
$modelsDir = __DIR__ . '/app/Models/';

$models = [
    'User' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Foundation\Auth\User as Authenticatable;\nuse Illuminate\Notifications\Notifiable;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass User extends Authenticatable\n{\n    use HasFactory, Notifiable, HasUuids;\n\n    protected \$fillable = ['name', 'email', 'password', 'role'];\n    protected \$hidden = ['password', 'remember_token'];\n    protected function casts(): array { return ['email_verified_at' => 'datetime', 'password' => 'hashed']; }\n\n    public function smartWeightProfiles(): HasMany { return \$this->hasMany(SmartWeightProfile::class); }\n}\n",
    'Team' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Team extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['name', 'region', 'logo_url', 'vlr_team_id'];\n\n    public function players(): HasMany { return \$this->hasMany(Player::class); }\n    public function matchesAsTeamA(): HasMany { return \$this->hasMany(MatchData::class, 'team_a_id'); }\n    public function matchesAsTeamB(): HasMany { return \$this->hasMany(MatchData::class, 'team_b_id'); }\n}\n",
    'Player' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Player extends Model\n{\n    use HasUuids;\n    const UPDATED_AT = null;\n    protected \$fillable = ['name', 'ign', 'country', 'team_id', 'current_role', 'vlr_player_id'];\n\n    public function team(): BelongsTo { return \$this->belongsTo(Team::class); }\n    public function mapStats(): HasMany { return \$this->hasMany(PlayerMapStat::class); }\n    public function criteriaScores(): HasMany { return \$this->hasMany(PlayerCriteriaScore::class); }\n    public function smartResults(): HasMany { return \$this->hasMany(PlayerSmartResult::class); }\n}\n",
    'Patch' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Patch extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['version', 'release_date', 'patch_notes_url'];\n\n    public function matches(): HasMany { return \$this->hasMany(MatchData::class); }\n    public function agentPatchRatings(): HasMany { return \$this->hasMany(AgentPatchRating::class); }\n    public function agentMapRatings(): HasMany { return \$this->hasMany(AgentMapRating::class); }\n    public function pickRateSnapshots(): HasMany { return \$this->hasMany(AgentPickRateSnapshot::class); }\n}\n",
    'Event' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Event extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['name', 'tier', 'region', 'season', 'start_date', 'end_date', 'vlr_event_id'];\n\n    public function matches(): HasMany { return \$this->hasMany(MatchData::class); }\n}\n",
    'StageLabelMapping' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\n\nclass StageLabelMapping extends Model\n{\n    use HasUuids;\n    protected \$table = 'stage_label_mapping';\n    public \$timestamps = false;\n    protected \$fillable = ['raw_label', 'normalized_stage', 'pressure_weight'];\n}\n",
    'MatchData' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass MatchData extends Model\n{\n    use HasUuids;\n    protected \$table = 'matches';\n    public \$timestamps = false;\n    protected \$fillable = ['event_id', 'team_a_id', 'team_b_id', 'patch_id', 'stage_label_id', 'match_date', 'best_of', 'raw_stage_label', 'vlr_match_id'];\n\n    public function event(): BelongsTo { return \$this->belongsTo(Event::class); }\n    public function teamA(): BelongsTo { return \$this->belongsTo(Team::class, 'team_a_id'); }\n    public function teamB(): BelongsTo { return \$this->belongsTo(Team::class, 'team_b_id'); }\n    public function patch(): BelongsTo { return \$this->belongsTo(Patch::class); }\n    public function stageLabelMapping(): BelongsTo { return \$this->belongsTo(StageLabelMapping::class, 'stage_label_id'); }\n    public function maps(): HasMany { return \$this->hasMany(Map::class, 'match_id'); }\n}\n",
    'Map' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass Map extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['match_id', 'map_name', 'winner_team_id', 'map_order'];\n\n    public function matchData(): BelongsTo { return \$this->belongsTo(MatchData::class, 'match_id'); }\n    public function winnerTeam(): BelongsTo { return \$this->belongsTo(Team::class, 'winner_team_id'); }\n    public function playerStats(): HasMany { return \$this->hasMany(PlayerMapStat::class); }\n}\n",
    'PlayerMapStat' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass PlayerMapStat extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['player_id', 'map_id', 'role_at_time_of_match', 'agent_played', 'acs', 'kast', 'adr', 'kd', 'first_kills', 'first_deaths', 'clutch_wins', 'rating'];\n\n    public function player(): BelongsTo { return \$this->belongsTo(Player::class); }\n    public function map(): BelongsTo { return \$this->belongsTo(Map::class); }\n}\n",
    'AgentRoleMap' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\n\nclass AgentRoleMap extends Model\n{\n    protected \$table = 'agent_role_map';\n    protected \$primaryKey = 'agent';\n    public \$incrementing = false;\n    protected \$keyType = 'string';\n    public \$timestamps = false;\n    protected \$fillable = ['agent', 'primary_role', 'secondary_role'];\n}\n",
    'AgentPatchRating' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass AgentPatchRating extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['patch_id', 'agent', 'role', 'tier', 'direction', 'notes'];\n\n    public function patch(): BelongsTo { return \$this->belongsTo(Patch::class); }\n}\n",
    'AgentMapRating' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass AgentMapRating extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['patch_id', 'agent', 'map', 'score', 'effective_date', 'source_reference', 'confidence_level', 'superseded_by_id'];\n\n    public function patch(): BelongsTo { return \$this->belongsTo(Patch::class); }\n    public function supersededBy(): BelongsTo { return \$this->belongsTo(AgentMapRating::class, 'superseded_by_id'); }\n}\n",
    'AgentPickRateSnapshot' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass AgentPickRateSnapshot extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['patch_id', 'agent', 'map', 'region', 'pick_rate', 'win_rate', 'snapshot_date', 'source'];\n\n    public function patch(): BelongsTo { return \$this->belongsTo(Patch::class); }\n}\n",
    'SmartCriteria' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\nuse Illuminate\Database\Eloquent\Relations\HasOne;\n\nclass SmartCriteria extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['name', 'type', 'description'];\n\n    public function defaultFilters(): HasMany { return \$this->hasMany(SmartFilterCriteria::class, 'criteria_id'); }\n}\n",
    'SmartWeightProfile' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\nuse Illuminate\Database\Eloquent\Relations\HasMany;\n\nclass SmartWeightProfile extends Model\n{\n    use HasUuids;\n    const UPDATED_AT = null;\n    protected \$fillable = ['user_id', 'name', 'is_public'];\n\n    public function user(): BelongsTo { return \$this->belongsTo(User::class); }\n    public function weightValues(): HasMany { return \$this->hasMany(SmartWeightValue::class, 'profile_id'); }\n    public function queryFilters(): HasMany { return \$this->hasMany(SearchQueryFilter::class, 'profile_id'); }\n}\n",
    'SmartWeightValue' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass SmartWeightValue extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['profile_id', 'criteria_id', 'rank_position', 'computed_weight'];\n\n    public function profile(): BelongsTo { return \$this->belongsTo(SmartWeightProfile::class, 'profile_id'); }\n    public function criteria(): BelongsTo { return \$this->belongsTo(SmartCriteria::class, 'criteria_id'); }\n}\n",
    'SmartFilterCriteria' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass SmartFilterCriteria extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['criteria_id', 'filter_type', 'default_value'];\n\n    public function criteria(): BelongsTo { return \$this->belongsTo(SmartCriteria::class, 'criteria_id'); }\n}\n",
    'SearchQueryFilter' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass SearchQueryFilter extends Model\n{\n    use HasUuids;\n    public \$timestamps = false;\n    protected \$fillable = ['profile_id', 'criteria_id', 'operator', 'value'];\n\n    public function profile(): BelongsTo { return \$this->belongsTo(SmartWeightProfile::class, 'profile_id'); }\n    public function criteria(): BelongsTo { return \$this->belongsTo(SmartCriteria::class, 'criteria_id'); }\n}\n",
    'PlayerCriteriaScore' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass PlayerCriteriaScore extends Model\n{\n    use HasUuids;\n    const UPDATED_AT = null;\n    const CREATED_AT = 'calculated_at';\n    protected \$fillable = ['player_id', 'criteria_id', 'patch_id', 'raw_value', 'global_normalized_utility', 'sample_size'];\n\n    public function player(): BelongsTo { return \$this->belongsTo(Player::class); }\n    public function criteria(): BelongsTo { return \$this->belongsTo(SmartCriteria::class, 'criteria_id'); }\n    public function patch(): BelongsTo { return \$this->belongsTo(Patch::class); }\n}\n",
    'PlayerSmartResult' => "<?php\n\nnamespace App\Models;\n\nuse Illuminate\Database\Eloquent\Model;\nuse Illuminate\Database\Eloquent\Concerns\HasUuids;\nuse Illuminate\Database\Eloquent\Relations\BelongsTo;\n\nclass PlayerSmartResult extends Model\n{\n    use HasUuids;\n    const UPDATED_AT = null;\n    const CREATED_AT = 'calculated_at';\n    protected \$fillable = ['player_id', 'profile_id', 'patch_id', 'mode', 'final_score', 'rank'];\n\n    public function player(): BelongsTo { return \$this->belongsTo(Player::class); }\n    public function profile(): BelongsTo { return \$this->belongsTo(SmartWeightProfile::class, 'profile_id'); }\n    public function patch(): BelongsTo { return \$this->belongsTo(Patch::class); }\n}\n"
];

foreach ($models as $name => $content) {
    file_put_contents($modelsDir . $name . '.php', $content);
}
echo "Models updated successfully.\n";
